### ISSUE TITLE
How is difficult to manipulate (hack) this storage?

### ISSUE THREAD

**Issue by TerkiKerel** [lhartikk/naivechain#15]
Hi,

Blockhain is a storage/database (which is using only some type of datas like transactions, logs, activity’s...).

I was researching this question for a long time. You code is simple. So I understand exactly how blockchain saves new datas up on old one...

But I have a question... I will be happy if you can help me here...

Why people says that it is difficult to manipulate the old data? A hacker can change the old data exactly like the other RMDS databases. 

We put the hash of the older block to new block. But the "hash" is only a string of the older block. So if someone will change the old block-data, no one will notice it.

Let say we have votes. We vote two government A and B. At the end of the day we have on blockhain:

Jack + A + hash0 + timestamp0
Maria + B + hash1 + timestamp1
Stephan + A + hash2 + timestamp2
Suzanna + A + hash3 + timestamp3
Tom + A + hash4 + timestamp4

Let say a hacker changed Stephan vode as B. So we will not notice that someone changed the vote (data). Because no one will recalculate every time timestamp3 (because) which is already added to blockhain.

I wanna tell that timestamp3 is calculation only once (when the new block will create). That's the problem...

Blockhain is good when it is distributed. But alone it is nothing. We can not calculate every hour all the blocks again and again. After a while (when the data will be more than terabytes) to re-calculate all blocks will be impossible/expensive.

Am I wrong?

*****this is wrong sentence. i was writing something different.*****
If blockhain is good when it is distributed why companies started to use it internally?
****************

Thank you

**Comment by jamilservicos** [comment]
"If blockhain is good when it is distributed why companies started to use it internally?"
I see the blockchain as a substitute for the famous ERP, where most of the transactions are entry/out of stock and sales. Which depend on a central database server.

Unfortunately people are using blockchain only for creating coins, and the possibilities for use are endless.

Another example would be the synchronization of user sessions between clusters. Decreasing the load of the central database server, we can synchronize the sessions via blockchain, distributed by the internal servers.

I may even be wrong in my assertion, but I do not believe that the blockchain is limited to just virtual currencies, as many have been using.

**Comment by adeora7** [comment]
@TerkiKerel Naivechain doesn't have any Proof of Work.Therefore, how will computation problem arise. Your answer in general for block chains is valid though (IMO). 

@jamilservicos +1 for the last line. In addition to that, blockchain is also being combined with existing relational databases to provide security of blockchain and save storage space at the same time.

**Comment by TerkiKerel** [comment]
Thank you for your comments...
