### ISSUE TITLE
Vulnerability when updating chain

### ISSUE THREAD

**Issue by miguescri** [lhartikk/naivechain#5]
Hi. I'm not familiar with JavaScript, so I hope I didn't miss something.

At the method **handleBlockchainResponse**, the default behaviour for a chain longer than the one of the user is invoquing **replaceChain**, which just takes the new one without checking if it extends the original one. By this, the blockchain can be tampered by anyone who knows the actual size of the current chain.

I know you want to keep the code simple, but I think this may be confusing for the educational purposes. 

My suggestion is modifying the method **isValidChain** so it takes a subchain and a pseudo-genesis block and be more generic. That way you could evaluate a whole blockchain from the Genesis Block or just the part of the received one that comes after the _latestBlockHeld_ (if the position _latestBlockHeld.index_ of the received chain contains _latestBlockHeld_, it ensures the previous ones with its hash, right?). Then you can add a protection with it to **replaceChain**.

I would do a merge request myself, but again, I dont speak JavaScript.

**Comment by fmsouza** [comment]
In this case, probably the algorithm would need to validate all the blockchain again every time a new blockchain with a new block is set to replace the existing one, what would be computationally unfeasible, or maybe just guarantee someway that the whole blockchain will always be valid by checking some kind of information, like a a hash which represents the whole structure.

In the second case, maybe it could be feasible, as each node already has the latest valid blockchain data, and consequently can calculate the whole blockchain SHA256, for example, and use this information to check if the new received blockchain SHA256 (the part without the new blocks), is compatible.
